language: php

php:
    - 7.0

before_script:
    - composer install --dev --prefer-dist --no-interaction

script: vendor/bin/phpunit --coverage-clover=coverage.clover --coverage-text

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
